### ISSUE TITLE
Crashes with MiniVitaTV plugin enabled

### ISSUE THREAD

**Issue by Poptheweasel100** [v-atamanenko/osu-octave#11] opened 2022-04-10 12:35 UTC
As the title says, I had the MiniVitaTV plugin enabled when attempting to boot the latest build. It gave me a C-12828-1 error. On a whim, I tried disabling the plugin, and it made the game work, but due to my other plugins I was unable to use any button controls. Hoping this could be fixed in a future build.

**Comment by v-atamanenko** [comment] 2022-04-10 13:02
@Poptheweasel100 thank you for your report. I will try to fix this as soon as possible.

**Comment by v-atamanenko** [comment] 2022-04-11 10:58
@Poptheweasel100 unfortunately, I was unable to reproduce the issue. Here is a video of me testing MiniVitaTV+ds4touch. https://youtu.be/2TZXrMBlvhY

Your issue must have been caused and solved with something else. (I'm thinking data files transfer method). I'm closing this issue for now and will reopen if any reproducible example of MiniVitaTV causing crashes appears. Thanks.

**Closed by v-atamanenko** 2022-04-11 10:58 UTC
Labels: bug, psvita
